In [ ]:
import pandas as pd
import numpy as np
import sys
from datetime import datetime
import pytz

In [ ]:
if 'google.colab' in sys.modules:
    from google.colab import drive
    drive.mount('/content/drive')
    path = '/content/drive/MyDrive/google_colab/dirty_dataset.csv'
else:
    path = 'dirty_dataset.csv'

df = pd.read_csv(path, sep=";")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 17 non-null     int64
 1   Nimi1              17 non-null     object
 2   Vanus              16 non-null     object
 3   Liitumise_Kuupäev  17 non-null     object
 4   Tööala             16 non-null     object
 5   Palk               12 non-null     float64
 6   Parkimine          7 non-null      object
dtypes: float64(1), int64(1), object(5)
memory usage: 1.1+ KB

In [ ]:
df.head()

    Id           Nimi1   Vanus Liitumise_Kuupäev   Tööala     Palk Parkimine
0  124  Alice  Johnson      25        2022-01-15       IT  50000.0      TRUE
1  152       Bob smith  thirty        2023/02/20       IT  19100.0       NaN
2  632   Charlie BRown      35        2023-01-15  Finance      NaN       NaN
3  853       David Lee      40        2022-04-05       IT  82040.0      TRUE
4  963       eve davis      29        2025-05-10       HR  55001.0     FALSE

In [ ]:
df.tail()

     Id          Nimi1   Vanus Liitumise_Kuupäev   Tööala     Palk Parkimine
12  142       Mark Oto  31 yrs        2023-11-01      Ops  48000.0      TRUE
13  245  Alice Johnson      25        2023-01-15       IT  50000.0      TRUE
14  486      Bob Smith  thirty        2023/02/20       IT  19100.0       NaN
15  989  Charlie Brown      35        2023-01-15  Finance      NaN       NaN
16  963  Charlie Brown      35        2023-01-15  Finance      NaN       NaN

In [ ]:
df.describe()

               Id          Palk
count   17.000000     12.000000
mean   563.823529  50290.916667
std    386.211282  17894.180138
min     84.000000  19100.000000
25%    142.000000  47250.000000
50%    632.000000  50025.000000
75%    963.000000  56250.750000
max    989.000000  82040.000000

In [ ]:
df.value_counts()

Id   Nimi1           Vanus   Liitumise_Kuupäev  Tööala   Palk     Parkimine
124  Alice  Johnson  25      2022-01-15         IT       50000.0  TRUE         1
142  Mark Oto        31 yrs  2023-11-01         Ops      48000.0  TRUE         1
245  Alice Johnson   25      2023-01-15         IT       50000.0  TRUE         1
853  David Lee       40      2022-04-05         IT       82040.0  TRUE         1
963  Tom Rivers      -5      2023-10-10         Finance  60000.0  FALSE        1
     eve davis       29      2025-05-10         HR       55001.0  FALSE        1
973  Maria Lint      twenty  2023-08-01         IT       45000.0  yes          1
Name: count, dtype: int64

In [ ]:
df_col_rename = df.copy()
df_col_rename.rename(columns={"Tööala": "Amet", "Liitumise_Kuupäev": "Liitumise_kuupäev"}, inplace=True)

In [ ]:
df_col_rename.head()

    Id           Nimi1   Vanus Liitumise_kuupäev     Amet     Palk Parkimine
0  124  Alice  Johnson      25        2022-01-15       IT  50000.0      TRUE
1  152       Bob smith  thirty        2023/02/20       IT  19100.0       NaN
2  632   Charlie BRown      35        2023-01-15  Finance      NaN       NaN
3  853       David Lee      40        2022-04-05       IT  82040.0      TRUE
4  963       eve davis      29        2025-05-10       HR  55001.0     FALSE

In [ ]:
df_name = df_col_rename.copy()

In [ ]:
df_name[["Eesnimi", "Perekonnanimi"]] = df_name["Nimi1"].str.split(" ", n=1, expand=True)

In [ ]:
df_name["Eesnimi"] = df_name["Eesnimi"].str.strip()
df_name["Eesnimi"] = df_name["Eesnimi"].str.title()

In [ ]:
df_name["Perekonnanimi"] = df_name["Perekonnanimi"].str.strip()
df_name["Perekonnanimi"] = df_name["Perekonnanimi"].str.title()

In [ ]:
df_name = df_name.drop(columns=["Nimi1"])

In [ ]:
df_name.head()

,Id,Vanus,Liitumise_kuupäev,Amet,Palk,Parkimine,Eesnimi,Perekonnanimi
0,124,25,2022-01-15,IT,50000.0,TRUE,Alice,Johnson
1,152,thirty,2023/02/20,IT,19100.0,NaN,Bob,Smith
2,632,35,2023-01-15,Finance,NaN,NaN,Charlie,Brown
3,853,40,2022-04-05,IT,82040.0,TRUE,David,Lee
4,963,29,2025-05-10,HR,55001.0,FALSE,Eve,Davis

In [ ]:
df_age = df_name.copy()

In [ ]:
df_age["Vanus"] = df_age["Vanus"].astype(str).str.extract(r'(\d+)')
df_age["Vanus"] = pd.to_numeric(df_age["Vanus"], errors="coerce")

In [ ]:
df_age.loc[(df_age["Vanus"] < 15) | (df_age["Vanus"] > 100), "Vanus"] = None

In [ ]:
df_age["Vanus"] = df_age["Vanus"].fillna(df_age["Vanus"].median())

In [ ]:
df_age["Vanus"] = df_age["Vanus"].astype(int)

In [ ]:
df_age = df_age[(df_age["Vanus"] >= 15) & (df_age["Vanus"] <= 100)]

In [ ]:
df_age["Vanus"].median()

30.0

In [ ]:
df_age["Vanus"].unique()

array([25, 30, 35, 40, 29, 28, 31])

In [ ]:
df_age.head()

,Id,Vanus,Liitumise_kuupäev,Amet,Palk,Parkimine,Eesnimi,Perekonnanimi
0,124,25,2022-01-15,IT,50000.0,TRUE,Alice,Johnson
1,152,30,2023/02/20,IT,19100.0,NaN,Bob,Smith
2,632,35,2023-01-15,Finance,NaN,NaN,Charlie,Brown
3,853,40,2022-04-05,IT,82040.0,TRUE,David,Lee
4,963,29,2025-05-10,HR,55001.0,FALSE,Eve,Davis

In [ ]:
df_date = df_age.copy()

In [ ]:
df_date["Liitumise_kuupäev"] = pd.to_datetime(
    df_date["Liitumise_kuupäev"].str.replace(".", "-", regex=False).str.replace("/", "-", regex=False),
    errors='coerce'
)

In [ ]:
df_date["Liitumise_kuupäev"] = df_date["Liitumise_kuupäev"].fillna(
    df_date["Liitumise_kuupäev"].median()
)

In [ ]:
print(df_age.columns.tolist())

['Id', 'Vanus', 'Liitumise_kuupäev', 'Amet', 'Palk', 'Parkimine', 'Eesnimi', 'Perekonnanimi']

In [ ]:
df_date

,Id,Vanus,Liitumise_kuupäev,Amet,Palk,Parkimine,Eesnimi,Perekonnanimi
0,124,25,2022-01-15,IT,50000.0,TRUE,Alice,Johnson
1,152,30,2023-02-20,IT,19100.0,NaN,Bob,Smith
2,632,35,2023-01-15,Finance,NaN,NaN,Charlie,Brown
3,853,40,2022-04-05,IT,82040.0,TRUE,David,Lee
4,963,29,2025-05-10,HR,55001.0,FALSE,Eve,Davis
5,84,30,2023-06-01,NaN,70200.0,NaN,Frank,Miller
6,905,25,2021-01-15,OP,50050.0,NaN,Alice,Johnson
7,863,28,2014-07-15,HR,NaN,NaN,Hanna,Wilson
8,137,30,2023-07-10,FI,NaN,NaN,Ryan,Sapr
9,973,30,2023-08-01,IT,45000.0,yes,Maria,Lint
10,963,30,2023-10-10,Finance,60000.0,FALSE,Tom,Rivers
11,111,30,2023-07-20,HR,55000.0,NaN,Jane,K
12,142,31,2023-11-01,Ops,48000.0,TRUE,Mark,Oto
13,245,25,2023-01-15,IT,50000.0,TRUE,Alice,Johnson
14,486,30,2023-02-20,IT,19100.0,NaN,Bob,Smith
15,989,35,2023-01-15,Finance,NaN,NaN,Charlie,Brown
16,963,35,2023-01-15,Finance,NaN,NaN,Charlie,Brown

In [ ]:
df_salary = df_date.copy()

In [ ]:
df_salary["Palk"] = pd.to_numeric(df_salary["Palk"], errors="coerce")

In [ ]:
df_salary["Palk"] = df_salary["Palk"].fillna(
    round(df_salary["Palk"].mean())
)

In [ ]:
df_salary["Palk"] = df_salary["Palk"].astype(int)

In [ ]:
df_salary.head()

,Id,Vanus,Liitumise_kuupäev,Amet,Palk,Parkimine,Eesnimi,Perekonnanimi
0,124,25,2022-01-15,IT,50000,TRUE,Alice,Johnson
1,152,30,2023-02-20,IT,19100,NaN,Bob,Smith
2,632,35,2023-01-15,Finance,50291,NaN,Charlie,Brown
3,853,40,2022-04-05,IT,82040,TRUE,David,Lee
4,963,29,2025-05-10,HR,55001,FALSE,Eve,Davis

In [ ]:
df_dropped = df_salary.copy()

In [ ]:
if "Parkimine" in df_dropped.columns:
    df_dropped.drop(columns=["Parkimine"], inplace=True)

In [ ]:
df_dropped.head()

    Id  Vanus Liitumise_kuupäev     Amet   Palk  Eesnimi Perekonnanimi
0  124     25        2022-01-15       IT  50000    Alice       Johnson
1  152     30        2023-02-20       IT  19100      Bob         Smith
2  632     35        2023-01-15  Finance  50291  Charlie         Brown
3  853     40        2022-04-05       IT  82040    David           Lee
4  963     29        2025-05-10       HR  55001      Eve         Davis

In [ ]:
df_title = df_dropped.copy()

In [ ]:
df_title["Amet"] = df_title["Amet"].replace({
    "Finance": "FI",
    "Human Resources": "HR",
    "Ops": "OP",

})

In [ ]:
mode_amet = df_title["Amet"].mode()[0]
df_title["Amet"] = df_title["Amet"].fillna(mode_amet)

In [ ]:
df_title["Amet"].unique()

array(['IT', 'FI', 'HR', 'OP'], dtype=object)

In [ ]:
df_title

     Id  Vanus Liitumise_kuupäev Amet   Palk  Eesnimi Perekonnanimi
0   124     25        2022-01-15   IT  50000    Alice       Johnson
1   152     30        2023-02-20   IT  19100      Bob         Smith
2   632     35        2023-01-15   FI  50291  Charlie         Brown
3   853     40        2022-04-05   IT  82040    David           Lee
4   963     29        2025-05-10   HR  55001      Eve         Davis
5    84     30        2023-06-01   IT  70200    Frank        Miller
6   905     25        2021-01-15   OP  50050    Alice       Johnson
7   863     28        2014-07-15   HR  50291    Hanna        Wilson
8   137     30        2023-07-10   FI  50291     Ryan          Sapr
9   973     30        2023-08-01   IT  45000    Maria          Lint
10  963     30        2023-10-10   FI  60000      Tom        Rivers
11  111     30        2023-07-20   HR  55000     Jane             K
12  142     31        2023-11-01   OP  48000     Mark           Oto
13  245     25        2023-01-15   IT  50000    Alice       Johnson
14  486     30        2023-02-20   IT  19100      Bob         Smith
15  989     35        2023-01-15   FI  50291  Charlie         Brown
16  963     35        2023-01-15   FI  50291  Charlie         Brown

In [ ]:
df_dupl = df_title.copy()

In [ ]:
df_dupl["Eesnimi"] = df_dupl["Eesnimi"].str.strip().str.capitalize()
df_dupl["Perekonnanimi"] = df_dupl["Perekonnanimi"].str.strip().str.title()

In [ ]:
df_dupl = df_dupl.drop_duplicates(
    subset=["Eesnimi","Perekonnanimi"],
    keep="first"
)

In [ ]:
print("df_title rows:", len(df_title))
print("df_dupl rows:", len(df_dupl))

df_title rows: 17
df_dupl rows: 12

In [ ]:
len(df_dupl)

12

In [ ]:
print(df_dupl.index)

Index([0, 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12], dtype='int64')

In [ ]:
df_dt = df_dupl.copy()

In [ ]:
from datetime import datetime

In [ ]:
df_dt["Aastat_liitumisest"] = df_dt["Liitumise_kuupäev"].apply(
    lambda x: (datetime.now() - x).days // 365 if pd.notnull(x) else None
)

In [ ]:
df_dt

,Id,Vanus,Liitumise_kuupäev,Amet,Palk,Eesnimi,Perekonnanimi,Aastat_liitumisest
0,124,25,2022-01-15,IT,50000,Alice,Johnson,4
1,152,30,2023-02-20,IT,19100,Bob,Smith,3
2,632,35,2023-01-15,FI,50291,Charlie,Brown,3
3,853,40,2022-04-05,IT,82040,David,Lee,3
4,963,29,2025-05-10,HR,55001,Eve,Davis,0
5,84,30,2023-06-01,IT,70200,Frank,Miller,2
7,863,28,2014-07-15,HR,50291,Hanna,Wilson,11
8,137,30,2023-07-10,FI,50291,Ryan,Sapr,2
9,973,30,2023-08-01,IT,45000,Maria,Lint,2
10,963,30,2023-10-10,FI,60000,Tom,Rivers,2
11,111,30,2023-07-20,HR,55000,Jane,K,2
12,142,31,2023-11-01,OP,48000,Mark,Oto,2

In [ ]:
df_cat = df_dt.copy()

In [ ]:
def palk_kategooria(palk):
    if pd.isna(palk):
        return np.nan
    elif 0 <= palk < 30000:
        return "madal"
    elif 30000 <= palk <= 59999:
        return "keskmine"
    elif palk >= 60000:
        return "kõrge"
    else:
        return np.nan

In [ ]:
df_cat["Palk_kategooria"] = df_cat["Palk"].apply(palk_kategooria)

In [ ]:
df_cat

,Id,Vanus,Liitumise_kuupäev,Amet,Palk,Eesnimi,Perekonnanimi,Aastat_liitumisest,Palk_kategooria
0,124,25,2022-01-15,IT,50000,Alice,Johnson,4,keskmine
1,152,30,2023-02-20,IT,19100,Bob,Smith,3,madal
2,632,35,2023-01-15,FI,50291,Charlie,Brown,3,keskmine
3,853,40,2022-04-05,IT,82040,David,Lee,3,kõrge
4,963,29,2025-05-10,HR,55001,Eve,Davis,0,keskmine
5,84,30,2023-06-01,IT,70200,Frank,Miller,2,kõrge
7,863,28,2014-07-15,HR,50291,Hanna,Wilson,11,keskmine
8,137,30,2023-07-10,FI,50291,Ryan,Sapr,2,keskmine
9,973,30,2023-08-01,IT,45000,Maria,Lint,2,keskmine
10,963,30,2023-10-10,FI,60000,Tom,Rivers,2,kõrge
11,111,30,2023-07-20,HR,55000,Jane,K,2,keskmine
12,142,31,2023-11-01,OP,48000,Mark,Oto,2,keskmine

In [ ]:
df_hoone = pd.DataFrame({
    "Id": [124,152,632,853,963,84,863,973,111,142],
    "Hoone": ["A","B","C","A","C","B","A","A","B","C"]
})

In [ ]:
df_merged = pd.merge(df_cat, df_hoone, on="Id")

In [ ]:
df_merged

,Id,Vanus,Liitumise_kuupäev,Amet,Palk,Eesnimi,Perekonnanimi,Aastat_liitumisest,Palk_kategooria,Hoone
0,124,25,2022-01-15,IT,50000,Alice,Johnson,4,keskmine,A
1,152,30,2023-02-20,IT,19100,Bob,Smith,3,madal,B
2,632,35,2023-01-15,FI,50291,Charlie,Brown,3,keskmine,C
3,853,40,2022-04-05,IT,82040,David,Lee,3,kõrge,A
4,963,29,2025-05-10,HR,55001,Eve,Davis,0,keskmine,C
5,84,30,2023-06-01,IT,70200,Frank,Miller,2,kõrge,B
6,863,28,2014-07-15,HR,50291,Hanna,Wilson,11,keskmine,A
7,973,30,2023-08-01,IT,45000,Maria,Lint,2,keskmine,A
8,963,30,2023-10-10,FI,60000,Tom,Rivers,2,kõrge,C
9,111,30,2023-07-20,HR,55000,Jane,K,2,keskmine,B
10,142,31,2023-11-01,OP,48000,Mark,Oto,2,keskmine,C

In [ ]:
df_sort = df_merged.copy()

In [ ]:
df_sort = df_sort.sort_values("Liitumise_kuupäev", ascending=False).reset_index(drop=True)

In [ ]:
df_sort

,Id,Vanus,Liitumise_kuupäev,Amet,Palk,Eesnimi,Perekonnanimi,Aastat_liitumisest,Palk_kategooria,Hoone
0,963,29,2025-05-10,HR,55001,Eve,Davis,0,keskmine,C
1,142,31,2023-11-01,OP,48000,Mark,Oto,2,keskmine,C
2,963,30,2023-10-10,FI,60000,Tom,Rivers,2,kõrge,C
3,973,30,2023-08-01,IT,45000,Maria,Lint,2,keskmine,A
4,111,30,2023-07-20,HR,55000,Jane,K,2,keskmine,B
5,84,30,2023-06-01,IT,70200,Frank,Miller,2,kõrge,B
6,152,30,2023-02-20,IT,19100,Bob,Smith,3,madal,B
7,632,35,2023-01-15,FI,50291,Charlie,Brown,3,keskmine,C
8,853,40,2022-04-05,IT,82040,David,Lee,3,kõrge,A
9,124,25,2022-01-15,IT,50000,Alice,Johnson,4,keskmine,A
10,863,28,2014-07-15,HR,50291,Hanna,Wilson,11,keskmine,A

In [ ]:
df_col_sorted = df_sort.copy()

In [ ]:
final_columns = ["Id","Liitumise_kuupäev","Aastat_liitumisest","Amet","Eesnimi","Perekonnanimi",
                 "Palk","Palk_kategooria","Vanus"]

In [ ]:
df_col_sorted = df_col_sorted[final_columns]

In [ ]:
df_col_sorted

,Id,Liitumise_kuupäev,Aastat_liitumisest,Amet,Eesnimi,Perekonnanimi,Palk,Palk_kategooria,Vanus
0,963,2025-05-10,0,HR,Eve,Davis,55001,keskmine,29
1,142,2023-11-01,2,OP,Mark,Oto,48000,keskmine,31
2,963,2023-10-10,2,FI,Tom,Rivers,60000,kõrge,30
3,973,2023-08-01,2,IT,Maria,Lint,45000,keskmine,30
4,111,2023-07-20,2,HR,Jane,K,55000,keskmine,30
5,84,2023-06-01,2,IT,Frank,Miller,70200,kõrge,30
6,152,2023-02-20,3,IT,Bob,Smith,19100,madal,30
7,632,2023-01-15,3,FI,Charlie,Brown,50291,keskmine,35
8,853,2022-04-05,3,IT,David,Lee,82040,kõrge,40
9,124,2022-01-15,4,IT,Alice,Johnson,50000,keskmine,25
10,863,2014-07-15,11,HR,Hanna,Wilson,50291,keskmine,28

In [ ]:
from datetime import datetime
import pytz


est_timezone = pytz.timezone('Europe/Tallinn')

# Get the current time in Estonian timezone and format it to include time
timestamp = datetime.now(est_timezone).strftime("%Y%m%d_%H%M%S")

if "google.colab" in sys.modules:
    path = f"/content/drive/MyDrive/google_colab/clean_dataset_{timestamp}.csv"
else:
    path = f"clean_dataset_{timestamp}.csv"

df_col_sorted.to_csv(path, index=False)